# Generated by Django 5.0.8 on 2024-08-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_sub_category_alter_track_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
