# Generated by Django 5.0.8 on 2024-09-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_track_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='credits',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True),
        ),
    ]
