version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: perfectsound_server
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE:core.settings.dev
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: perfectsound_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - perfectsound_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: perfectsound_redis

volumes:
  perfectsound_data:
