# Generated by Django 5.0.8 on 2024-08-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Is email verified?')),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile number')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0, null=True, verbose_name='Gender')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Permanent address')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('post_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Post code')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('join_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Join date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_2fa', models.BooleanField(default=False, verbose_name='Is 2FA?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-join_date',),
            },
        ),
    ]
