# Generated by Django 5.0.8 on 2024-08-16 14:27

import account.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('code', models.IntegerField(blank=True, default=account.utils.utils.generate_otp, null=True, verbose_name='Code')),
            ],
        ),
    ]
