# Generated by Django 5.0.8 on 2024-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='newsletters/')),
            ],
        ),
    ]
