# Generated by Django 5.0.8 on 2024-08-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_street_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Promo Code'),
        ),
    ]
