# Generated by Django 5.0.8 on 2024-08-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
