name: Build and push docker image to digitalocean

on:
  push:
    branches:
      - main
      - stable

jobs:
  dev-build:
    runs-on: bem-runner
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Github Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image (dev)
        run: |
          docker build -f ./server/Dockerfile . -t ghcr.io/${{ github.repository }}/britishpresscouk:dev
          docker push ghcr.io/${{ github.repository }}/britishpresscouk:dev
    
  production-build:
    runs-on: bem-runner
    if: github.ref == 'refs/heads/stable'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Github Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build and push Docker image (dev)
        run: |
          docker build -f ./server/Dockerfile . -t ghcr.io/${{ github.repository }}/britishpresscouk:prod
          docker push ghcr.io/${{ github.repository }}/britishpresscouk:prod
  
  production:
    needs: production-build 
    runs-on: bem-runner
    if: github.ref == 'refs/heads/stable'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Deploy to Production
        run: |
          echo ""
