# Generated by Django 5.0.8 on 2024-08-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePlanCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, choices=[(0, 'Month'), (1, 'Six Month'), (2, 'Annual'), (3, 'Custom')], null=True)),
                ('duration_unit', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, max_length=755, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True)),
                ('credit', models.ManyToManyField(related_name='priceplans', to='payment.priceplancredit')),
            ],
        ),
    ]
