# Generated by Django 5.0.8 on 2024-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Plan Amount'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='credit',
            field=models.ManyToManyField(to='payment.priceplancredit'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='description',
            field=models.TextField(blank=True, max_length=755, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='duration',
            field=models.CharField(blank=True, choices=[(0, 'Month'), (1, 'Six Month'), (2, 'Annual'), (3, 'Custom')], null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='duration_unit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Duration Unit'),
        ),
        migrations.AlterField(
            model_name='priceplancredit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='priceplancredit',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Credit Value'),
        ),
    ]
