# Generated by Django 5.0.8 on 2024-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_promocode_alter_priceplan_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='credit',
            field=models.ManyToManyField(blank=True, to='payment.priceplancredit'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='duration',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('six_month', 'Six Month'), ('annual', 'Annual'), ('custom', 'Custom')], default='month', null=True, verbose_name='Duration'),
        ),
    ]
