# Generated by Django 5.0.8 on 2024-08-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_priceplan_credit_alter_priceplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Serial Order'),
        ),
    ]
