# Generated by Django 5.0.8 on 2024-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_priceplan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='priceplan',
            name='duration',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('annual', 'Annual'), ('custom', 'Custom')], default='month', null=True, verbose_name='Duration'),
        ),
    ]
