# Generated by Django 5.0.8 on 2024-08-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_priceplan_title_alter_priceplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='duration',
            field=models.CharField(blank=True, choices=[('week', 'Week'), ('month', 'Month'), ('year', 'Year'), ('custom', 'Custom')], default='month', null=True, verbose_name='Duration'),
        ),
    ]
