# Generated by Django 5.0.8 on 2024-08-30 14:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_priceplan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
