# Generated by Django 5.0.8 on 2024-08-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_priceplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='percentage',
            field=models.IntegerField(default=0, verbose_name='Percentage'),
        ),
    ]
