# Generated by Django 5.0.8 on 2024-09-09 14:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_promocode_end_date_promocode_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceplan',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
