# Generated by Django 5.0.8 on 2024-09-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_priceplan_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], max_length=65)),
                ('stripe_id', models.CharField(blank=True, help_text='Stripe Payment Method ID (If Stripe is used)', max_length=255, null=True)),
                ('paypal_id', models.CharField(blank=True, help_text='PayPal Account ID (if PayPal is used)', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='save_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
