# Generated by Django 5.0.8 on 2024-09-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_stripecustomer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
    ]
